### ISSUE TITLE
No Need to AutoCmd "set number" in every buffer

### ISSUE THREAD

**Issue by ketor** [tkhoa2711/vim-togglenumber#4]
I use NerdTree and Tagbar, and also use vim-togglenumber.
I see that vim-togglenumber will "set number" in all buffer, but I think in NerdTree and Tagbar or some other buffers we don't need line numbers.
And users will mostly define if "set number" in their .vimrc file.
So would you please consider delete the AutoCmd of "set number"?

Thanks!

**Comment by ketor** [comment]
autocmd BufEnter \* :set number

This is the code I refered to.

**Comment by tkhoa2711** [comment]
I also use NerdTree but I don't see it is set to number mode in the NerdTree's buffer. Though I've been considering remove that line of code for a while since it also causes issue #1.

**Comment by tkhoa2711** [comment]
I commit the change. That should fix it.

**Comment by ketor** [comment]
Thank you very much!
Now all is OK! vim-togglenumber is the cool!
